### ISSUE TITLE
text markup system

### ISSUE THREAD

**Issue by seanmakesgames** [DrizzlyBear/u3d_text_3ngine#3]
Need to be able to specify colors on a 'least-verbose' basis, but allowing per-character coloring.
52 colors need to be supported: currently represented by a-zA-Z

Current idea: parser with 'color mode'; set color (foreground/background) with a specific character and that color is set until color is changed or end of string is reached

**Comment by Simoyd** [comment]
In my experience, RTF is really fast. What I'm thinking is to store the text on a 'least-verbose' basis, figure out what part of that text should be on screen (based on width, scroll, etc), then generating an RTF string any time something changes (user scrolls, new text appears, user resizes) to contain only the text that is on-screen. This would however limit the per-character things that RTF doesn't support (like the special effects on new text, hence the comment in the other issue).

**Comment by seanmakesgames** [comment]
Don't worry about the cutting / paging systems at this point, that code will be moved out of hm codebase and into this one when the time is right.
RTF is kind of verbose to-spec; Are you thinking of a modified impl. or is there an RTF implementation over a text field for coloring already and we can fit in it?

**Comment by Simoyd** [comment]
I'd like to try to use as much of the built-in unity stuff as possible to begin with, to get a better understanding of the limits of the system. It appears that unity has some built-in support for RTF that I would like to play with. It is verbose, but I think the RTF would only be internal to the 'text object' and not exposed outside. I understand memory usage is a problem here too. I need to play with it a bit and see what performance looks like. What font does hack-mud use? It would be nice to use the same one for my testing.

**Comment by seanmakesgames** [comment]
Actually unity's built-in rendering is the problem. It doesn't handle large numbers of colors well. (which is the basis of this repo and one of the fundamental problems we are trying to fix with this implementation)

**Comment by Simoyd** [comment]
Ok, my first thought to that is maybe to have a separate canvas/mesh per text line, and abstract the lines with another object. This might meet the requirements without needing custom text rendering. Does hackmud currently support the full unicode character set?

**Comment by Simoyd** [comment]
https://www.assetstore.unity3d.com/en/#!/content/84126

^ Have you seen this? It's free, but only became free very recently. Seems to have many good reviews. I will try this out.

**Comment by seanmakesgames** [comment]
full unicode is supported by OS fallbacks.
Font will be checked-in later today.

canvas / mesh per text line could work, but part of the future requirements is to be able to color background/foreground of characters independently.
Also, using mesh-per-line doesn't allow call batching across colors. We would see pretty great performance if we got to one draw call per color

**Comment by seanmakesgames** [comment]
definitely worth trying. Even though I said that stuff in the last comment, this repo currently is mostly concerned with pulling some of this code into the open-source space so that these features can be contributed by players.

**Comment by n00bish** [comment]
I took this on per our discussions in discord - color tag formatting as implemented in my PR:
`<cFBtext>` where `F` is a valid foreground specifier and `B` is a valid background specifier.
Using `*` as a specifier will preserve last color applied to the text in foreground or background respectively.
