### ISSUE TITLE
Make main CS file easier to vet for safety (and vet it)

### ISSUE THREAD

**Issue by ethankaminski** [DrizzlyBear/u3d_text_3ngine#7]
I'm a bit uneasy with a 600 line file that includes some dense lines and, at the top, a blanket `using System.Diagnostics;`. Would be good if we narrowed that down, so that it's harder to slip potentially-dangerous stuff in (whether deliberately or accidentally).

**Comment by seanmakesgames** [comment]
This is in reference to #6 -- using Sys.diag will be changed before pr is accepted.

**Comment by Simoyd** [comment]
should be good now

**Comment by seanmakesgames** [comment]
vetted.
